### ISSUE TITLE
How does this compare with serde_urlencoded?

### ISSUE THREAD

**Issue by dtolnay** [boxdot/serde-url-params-rs#7]
https://github.com/nox/serde_urlencoded

Any advantages of one or the other?

**Comment by boxdot** [comment]
Thanks for providing the reference. I was looking for such a library, and apparently overlooked this one. So, I decided to write my own.

I don't think there is any advantage of using mine, since it lacks deserialization, and much more. I will port my code using this lib to `serde_urlencoded`, and then delete the crate.

**Comment by boxdot** [comment]
`serde_urlencoded` does not support:

```
struct A {
  seq: Vec<String>
}
```

which is serialized to

`seq=elem1&seq=elem2`

by this crate.
